### ISSUE TITLE
Calendar Date pick is crazy

### ISSUE THREAD

**Issue by johanguse** [nainglinnkhant/shadcn-view-table#3] opened 2024-07-09 22:04 UTC
When I picked one date, the calendar didn't stop changing the date

https://github.com/nainglinnkhant/shadcn-view-table/assets/6184866/0daf39c3-e877-432f-8570-9af7c46df1ed

**Comment by nainglinnkhant** [comment] 2024-07-10 08:26
Thanks for the heads up. Could you please specify how can I reproduce it?

**Comment by johanguse** [comment] 2024-07-10 12:32
No secret... open the URL and try to change the date on the calendar, and the error happens.
I've use Chrome (Version 126.0.6478.127 (Official Build) (64-bit)) with AdBlock on Windows OS

> Thanks for the heads up. Could you please specify how can I reproduce it?

**Comment by nainglinnkhant** [comment] 2024-07-10 22:41
It doesn't happen on my end (MacOS but the same Chrome version as you) and I don't have a Windows device to debug it. While I'm unable to find a way to debug it, could you check if the issue is solved in [this preview](https://shadcn-view-table-k684iq481-nainglinnkhants-projects.vercel.app)?

**Comment by nainglinnkhant** [comment] 2024-07-13 06:47
I've tested on the virtual env of Windows 10 and Windows 11 with the same Chrome version you use and didn't have this error. Can you specify more information about your environment or try it on incognito mode? @johanguse

**Comment by johanguse** [comment] 2024-07-14 13:47
Hey @nainglinnkhant, I can't access the preview link. I also tried on incognito mode, Firefox, Edge, and Opera, and all the browsers have the same error. on Edge and Opera I have zero extensions.

**Comment by nainglinnkhant** [comment] 2024-07-15 04:33
I see, I've just granted you access. Please check.

**Comment by johanguse** [comment] 2024-07-15 16:40
Yes, the problem was fixed on this link [[shadcn-view-table-git-fix-fix-d-63531b-nainglinnkhants-projects.vercel.app](https://c.knock.app/t/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjEwMTc5Njg1OTI1MDAsImlkeCI6MCwibWlkIjoiMmpHZWlaOEs1czUxUzFXb2doWmROSzJNWElnIiwidXJsIjoiaHR0cHM6Ly9zaGFkY24tdmlldy10YWJsZS1naXQtZml4LWZpeC1kLTYzNTMxYi1uYWluZ2xpbm5raGFudHMtcHJvamVjdHMudmVyY2VsLmFwcCJ9.YH05Z_a1XJnP-VJMpchNX-YofDjcol1swHg5Yi96efw)](https://shadcn-view-table-git-fix-fix-d-63531b-nainglinnkhants-projects.vercel.app/)

**Comment by nainglinnkhant** [comment] 2024-07-28 21:40
Thanks for your contribution. The fix's merged now. However, there's a tradeoff of the date picker not being updated with a new date when date params change in URL. But I think the bug that we're tackling in this issue is a more serious concern.

**Closed as completed** 2024-08-27 17:57 UTC
